# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [18]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:

import numpy as np
a = np.arange(1, 16).reshape(3,5)


In [8]:
import numpy as np
a = np.arange(1, 16).reshape(3,5)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype.name)

(3, 5)
2
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [20]:
b = np.arange(1, 10).reshape(3, 3)
c = np.ones((3, 3))*2

print("matris b")
print(b)
print()
print("matris c")
print(c)
print()
print("Elementwise subtraction")
print("matris a = matris b - matris c")
a = b - c
print(a)
print()
print("Elementwise multiplication")
print("matris a = matris b * matris c")
a = b * c
print(a)
print()
print("Matrix multiplication  matris a = b @ c")
a = b @ c
print(a)


matris b
[[1 2 3]
 [4 5 6]
 [7 8 9]]

matris c
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise subtraction
matris a = matris b - matris c
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication
matris a = matris b * matris c
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication  matris a = b @ c
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [21]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
D = np.arange(1, 10).reshape(3, 3)
print("Exponentiate D elementwise")
print(np.exp(D))

print("minimum value in the whole matrix")
print(np.min(D))

print("minimum value of each row")
print(D.min(axis=1))

print("minimum value of each column")
print(D.min(axis=0))   
print("the index value of the minimum value in the whole matrix")
print(np.argmin(D))
print("the index value of the minimum value in each row")
print(np.argmin(D, axis=1))
print("The sum for all elements")
print(D.sum())
print("The mean for each column")
print(np.mean(D, axis=0))
print("The median for each column")
print(np.median(D, axis=0))      

Exponentiate D elementwise
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
minimum value in the whole matrix
1
minimum value of each row
[1 4 7]
minimum value of each column
[1 2 3]
the index value of the minimum value in the whole matrix
0
the index value of the minimum value in each row
[0 0 0]
The sum for all elements
45
The mean for each column
[4. 5. 6.]
The median for each column
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [22]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# When fewer indices are provided than the number of axes
# the missing indices are considered complete slices
# in this caee A[1] means array of all columns of row 2


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [24]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [ ]:
# for i in A.flat:
#    print(i)
# the flat attribute which is an iterator
# returns a one column list with one element on each row

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [26]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# The code reshapes the matrix a
# from one axis to three axis
# -1 is a joker sign for numpy to caclulate the third axis
# (the column value) to five columns
# based on the input 3 rows and 2 blocks.



### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [27]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [28]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [29]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
import numpy as np
def add_mult_matrices(matrix1, matrix2, operation):
    
    
    
    """
    Defines the function "add_mult_matrices"    
    Validate datatypes 
    matrix1 and matrix2 are the two numpy.ndarray matrices 
    operation is either "add" or "multiply" as string value
    
    """
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Not valid matrice input")

    operation_select = ['add', 'multiply']
    if operation not in operation_select:
        raise TypeError("Not valid operation input")

    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Different matrix shapes")        
        return matrix1 + matrix2

    elif operation == 'multiply':      
        M1 = matrix1
        M2 = matrix2
        
        if M1.ndim == 2 and M2.ndim == 2:
             if M1.shape[1] != M2.shape[0]:
                raise ValueError("Columns in M1 does not match rows in M2."                )
        return M1 @ M2  

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [ ]:
import numpy as np
x=np.array([4, 3])
print("Uppgift 10.1.1 Definiera vektorn x enligt nedan")
print("(a) vektorn x=(4,3) har dimensionen 1x2")
print("(b) Beräkna 5x")
print(5*x)
print("(c) Beräkna 3x")
print(3*x)
print("(d) Beräkna 5x + 3x")
print((5*x)+(3*x))
print("(e) Beräkna 8x")
print(8*x)
print("(f) Beräkna 4x - x")
print((4*x)-x)
print("(g) Transponatet av x")
print(x.T)
print("(h) x + x.T är definierat")
print(x+x.T)
print("(i) Beräkna normen för x")
print(np.linalg.norm(x))
print("\nUppgift 10.1.2 Definiera kolumnvektorn v enligt nedan")
v = np.array([[3],
              [7],
              [0],
              [11]])
print(v)
print("(a) vektorn v (ovan) har dimensionen 4x1")
print("(b) Beräkna 2v")
print(2*v)
print("(c) Beräkna 5v + 2v")
print((5*v)+(2*v))
print("(d) Beräkna 4v - 2v")
print((5*v)+(2*v))
print("(e) Transponatet av v ger nya dimensionen 1x4")
print(v.T)
print("(f) Beräkna normen för v")
print(np.linalg.norm(v))
print("\n Uppgift 10.1.3 Definiera vektorerna")
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])
print(f"v1{v1} och v2{v2}") 
print("(a) Beräkna normen för v1")
print(np.linalg.norm(v1))
print("(b) Beräkna normen för v1-v2")
print(np.linalg.norm(v1-v2))



Uppgift 10.1.1 Definiera vektorn x enligt nedan
(a) vektorn x=(4,3) har dimensionen 1x2
(b) Beräkna 5x
[20 15]
(c) Beräkna 3x
[12  9]
(d) Beräkna 5x + 3x
[32 24]
(e) Beräkna 8x
[32 24]
(f) Beräkna 4x - x
[12  9]
(g) Transponatet av x
[4 3]
(h) x + x.T är definierat
[8 6]
(i) Beräkna normen för x
5.0

Uppgift 10.1.2 Definiera kolumnvektorn v enligt nedan
[[ 3]
 [ 7]
 [ 0]
 [11]]
(a) vektorn v (ovan) har dimensionen 4x1
(b) Beräkna 2v
[[ 6]
 [14]
 [ 0]
 [22]]
(c) Beräkna 5v + 2v
[[21]
 [49]
 [ 0]
 [77]]
(d) Beräkna 4v - 2v
[[21]
 [49]
 [ 0]
 [77]]
(e) Transponatet av v ger nya dimensionen 1x4
[[ 3  7  0 11]]
(f) Beräkna normen för v
13.379088160259652

 Uppgift 10.1.3 Definiera vektorerna
v1[4 3 1 5] och v2[2 3 1 1]
(a) Beräkna normen för v1
7.14142842854285
(a) Beräkna normen för v1-v2
4.47213595499958
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [15]:
import numpy as np
A=np.array([[2, 1, -1], 
            [1, -1, 1]])
B=np.array([[4, -2, 1], 
            [2, -4, -2]])
C=np.array([[1, 2], 
            [2, 1]])
D=np.array([[3, 4], 
            [4, 3]])
E=np.array([[1], 
            [2]])
I=np.array([[1, 0], 
            [0, 1]])
A2=np.array([[2, 3, 4], 
            [5, 4, 1]])
A3=np.array([[1, 2], 
            [2, 4]])
B3=np.array([[2, 1], 
            [1, 3]])
C3=np.array([[4, 3], 
            [0, 2]])



print("Uppgift 10.2.1 Definiera matriserna")
print(f"A=\n{A}")
print(f"B=\n{B}")
print(f"C=\n{C}")
print(f"D=\n{D}")
print(f"E=\n{E}")
print(f"I=\n{I}")
print("Om det är definierat, utför följande beräkningar")
print(f"(a) 2A = \n {2*A}")
print(f"(b) B - 2A = \n {B - (2*A)}")
print(f"(c) 3C - 2E = \n {(3*C) - (2*E)}")
print(f"(d) 2D - 3C = \n {(2*D) - (3*C)}")
print(f"(e) D.T + 2D = \n {D.T + (2*D)}")
print(f"(f) 2C.T - 2D.T = \n {(2*C.T) - (2*D.T)}")
print("(g) A.T - B = \n EJ DEFINIERAT")
print("(h) AC = \n EJ DEFINIERAT")
print(f"(i) CD = \n {C@D}")
print(f"(j) CB = \n {C@B}")
print(f"(k) CI = \n {C@I}")
print(f"(l) AC.T = \n {A@B.T}")
print("Uppgift 10.2.2 Definiera matrisen")
print(f"AA.T = \n {A2@A2.T}")
print("Uppgift 10.2.3 Definiera matriserna")
print(f"A=\n{A3}")
print(f"B=\n{B3}")
print(f"C=\n{C3}")
print(" Verifiera att AB=AC men att B!=C")
print("Visar att AB - AC = 0")
print(f"{(A3@B3) - (A3@C3)}")
print("Visar att B - C != 0")
print(f"{B3 - C3}")











Uppgift 10.2.1 Definiera matriserna
A=
[[ 2  1 -1]
 [ 1 -1  1]]
B=
[[ 4 -2  1]
 [ 2 -4 -2]]
C=
[[1 2]
 [2 1]]
D=
[[3 4]
 [4 3]]
E=
[[1]
 [2]]
I=
[[1 0]
 [0 1]]
Om det är definierat, utför följande beräkningar
(a) 2A = 
 [[ 4  2 -2]
 [ 2 -2  2]]
(b) B - 2A = 
 [[ 0 -4  3]
 [ 0 -2 -4]]
(c) 3C - 2E = 
 [[ 1  4]
 [ 2 -1]]
(d) 2D - 3C = 
 [[3 2]
 [2 3]]
(e) D.T + 2D = 
 [[ 9 12]
 [12  9]]
(f) 2C.T - 2D.T = 
 [[-4 -4]
 [-4 -4]]
(g) A.T - B = 
 EJ DEFINIERAT
(h) AC = 
 EJ DEFINIERAT
(i) CD = 
 [[11 10]
 [10 11]]
(j) CB = 
 [[  8 -10  -3]
 [ 10  -8   0]]
(k) CI = 
 [[1 2]
 [2 1]]
(l) AC.T = 
 [[5 2]
 [7 4]]
Uppgift 10.2.2 Definiera matrisen
AA.T = 
 [[29 26]
 [26 42]]
Uppgift 10.2.3 Definiera matriserna
A=
[[1 2]
 [2 4]]
B=
[[2 1]
 [1 3]]
C=
[[4 3]
 [0 2]]
 Verifiera att AB=AC men att B!=C
Visar att AB - AC = 0
[[0 0]
 [0 0]]
Visar att B - C != 0
[[-2 -2]
 [ 1  1]]


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [3]:
import numpy as np
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)


[0 1 2 3]
[2 3]


In [22]:
import numpy as np
v1 = np.arange(4)
v2 = v1[-2:]
print(f"v1 = {v1}")
print(f"v2 = {v2}")
print("How to check if v1 or v2 is a view or copy")
print("The base of an array (v1 = np.arange(4)) that owns its memory (as copy) is None")
print(f"v1 = {v1.base}")
print("Slicing ( v2 = v1[-2:]) creates a view, whose memory is shared with v1:")
print(f"v2 = {v2.base}")

print("\nWhat will happen if second element in v2 is changed to 123")
print("Will v1 also change accordingly?")


v2[1:2] = [123]
print(v2)
print(v1)

print(f"v1 = {v1.base}")
print(f"v2 = {v2.base}")

print("This happens because v2 shares memory with v1 (also called view)")

v1 = [0 1 2 3]
v2 = [2 3]
How to check if v1 or v2 is a view or copy
The base of an array (v1 = np.arange(4)) that owns its memory (as copy) is None
v1 = None
Slicing ( v2 = v1[-2:]) creates a view, whose memory is shared with v1:
v2 = [0 1 2 3]

What will happen if second element in v2 is changed to 123
Will v1 also change accordingly?
[  2 123]
[  0   1   2 123]
v1 = None
v2 = [  0   1   2 123]
This happens because v2 shares memory with v1 (also called view)
